baseURL = 'https://cc-eats.vercel.app/'
languageCode = 'en-us'
title = 'CC Eats'
theme = 'lugo'

[params]
  favicon = "/favicon.svg"
  stylesheet = "/style.css"
  indexarticles = 50
  taglist = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
